name: Evaluate_Unet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - numpy=1.19.2
  - opencv=4.1.2
  - tensorflow=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.0
  - notebook
  - matplotlib